"use client";

import { useState } from "react";
import { CheckCircle2, Download, FileText, ImagePlus, LifeBuoy, Mail, Phone, Receipt, Upload, Wrench, X } from "lucide-react";

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`rounded-2xl border border-[#ECEEED] bg-white p-5 shadow-sm ${className}`}>{children}</div>; }
const docs = [
  ["Tenancy agreement (AST)", "Executed · 30 Sep 2024", "PDF · 2.4 MB"],
  ["Rent receipt — September 2026", "Paid · 1 Sep 2026", "PDF · 184 KB"],
  ["Deposit protection certificate", "TDS · Protected 30 Sep 2024", "PDF · 620 KB"],
  ["Inventory check-in report", "Signed · 28 Sep 2024", "PDF · 4.1 MB"],
];

export function TenantDashboardWorkspace() {
  const [notice, setNotice] = useState<string | null>(null);
  return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-3"><Card><p className="text-xs text-gray-500">Rent status</p><p className="mt-3 flex items-center gap-2 text-2xl font-bold text-[#2A5240]"><CheckCircle2 className="h-5 w-5" /> Paid</p><p className="mt-1 text-xs text-gray-500">Next payment 1 October 2026</p></Card><Card><p className="text-xs text-gray-500">Monthly rent</p><p className="mt-3 text-2xl font-bold">£2,150</p><p className="mt-1 text-xs text-gray-500">Standing order active</p></Card><Card><p className="text-xs text-gray-500">Tenancy</p><p className="mt-3 text-2xl font-bold">Active</p><p className="mt-1 text-xs text-gray-500">8 Camden Mews · CM-08</p></Card></div><div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]"><Card><div className="flex items-center justify-between"><h2 className="font-semibold">Current tenancy</h2><span className="rounded-full bg-[#E8EFEA] px-3 py-1 text-xs font-semibold text-[#2A5240]">12 months remaining</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2 text-sm"><div><p className="text-xs text-gray-500">Address</p><p className="mt-1 font-medium">8 Camden Mews, London NW1 9UX</p></div><div><p className="text-xs text-gray-500">Lease dates</p><p className="mt-1 font-medium">1 Oct 2024 — 30 Sep 2027</p></div><div><p className="text-xs text-gray-500">Managing agent</p><p className="mt-1 font-medium">Haven Lettings</p></div><div><p className="text-xs text-gray-500">Open maintenance</p><p className="mt-1 font-medium">2 requests · 1 scheduled</p></div></div></Card><Card><h2 className="font-semibold">Your property team</h2><div className="mt-4 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#E8EFEA] font-semibold text-[#132A20]">HP</div><div><p className="font-medium">Haven Property Team</p><p className="text-xs text-gray-500">Available Mon–Fri, 9am–5pm</p></div></div><div className="mt-5 flex gap-2"><button onClick={() => setNotice("Calling Haven Property Team…")} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl border py-2 text-sm"><Phone className="h-4 w-4" /> Call</button><button onClick={() => setNotice("Message composer opened")} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl border py-2 text-sm"><Mail className="h-4 w-4" /> Message</button></div></Card></div><div className="flex flex-wrap gap-3"><button onClick={() => setNotice("Rent payment flow opened")} className="inline-flex items-center gap-2 rounded-xl bg-[#132A20] px-4 py-2.5 text-sm font-semibold text-white"><Receipt className="h-4 w-4" /> Pay Rent</button><button onClick={() => setNotice("Maintenance request form opened")} className="inline-flex items-center gap-2 rounded-xl border border-[#ECEEED] bg-white px-4 py-2.5 text-sm font-semibold"><Wrench className="h-4 w-4" /> Report Issue</button></div>{notice && <Toast message={notice} onClose={() => setNotice(null)} />}</div>;
}

function Toast({ message, onClose }: { message: string; onClose: () => void }) { return <div className="fixed bottom-5 right-5 z-50 flex items-center gap-3 rounded-xl bg-[#132A20] px-4 py-3 text-sm text-white shadow-xl"><CheckCircle2 className="h-4 w-4" />{message}<button onClick={onClose}><X className="h-4 w-4" /></button></div>; }

export function TenantMaintenanceWorkspace() {
  const [category, setCategory] = useState("Plumbing");
  const [submitted, setSubmitted] = useState(false);
  return <div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><Card><div className="flex items-center gap-2"><LifeBuoy className="h-5 w-5 text-[#2A5240]" /><h2 className="font-semibold">Report an issue</h2></div><p className="mt-2 text-sm text-gray-500">Tell us what needs attention and the property team will coordinate a repair.</p><div className="mt-6 space-y-5"><label className="block text-sm font-medium">Issue title<input placeholder="e.g. Bathroom tap is leaking" className="mt-2 h-10 w-full rounded-xl border border-[#ECEEED] px-3 text-sm" /></label><div><p className="text-sm font-medium">Category</p><div className="mt-2 flex flex-wrap gap-2">{["Plumbing", "Electrical", "Heating", "Appliance", "Other"].map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${category === item ? "bg-[#132A20] text-white" : "bg-[#F0F2F1] text-gray-600"}`}>{item}</button>)}</div></div><label className="block text-sm font-medium">Description<textarea placeholder="Add useful details, access notes or timing preferences" className="mt-2 min-h-28 w-full rounded-xl border border-[#ECEEED] p-3 text-sm" /></label><label className="flex cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-[#ECEEED] p-6 text-center"><ImagePlus className="h-7 w-7 text-gray-400" /><span className="mt-2 text-sm font-medium">Add photos of the issue</span><span className="mt-1 text-xs text-gray-500">PNG or JPG up to 10 MB</span><input type="file" accept="image/*" multiple className="sr-only" /></label><button onClick={() => setSubmitted(true)} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#132A20] py-3 text-sm font-semibold text-white"><Upload className="h-4 w-4" /> Submit request</button></div></Card><Card><h2 className="font-semibold">Request tracker</h2><div className="mt-6 space-y-6">{["Request submitted", "Property team reviewing", "Contractor scheduled", "Resolved"].map((item, index) => <div key={item} className="flex gap-3"><div className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full ${submitted || index === 0 ? "bg-[#132A20] text-white" : "bg-[#F0F2F1] text-gray-400"}`}>{index === 0 || (submitted && index < 2) ? <CheckCircle2 className="h-4 w-4" /> : <span className="text-xs">{index + 1}</span>}</div><div><p className="text-sm font-medium">{item}</p><p className="mt-1 text-xs text-gray-500">{index === 0 ? "MN-204 · Today, 09:42" : index === 1 ? "Usually within 4 hours" : "Pending next step"}</p></div></div>)}</div><div className="mt-8 rounded-xl bg-amber-50 p-4 text-xs leading-5 text-amber-900"><strong>Emergency?</strong> If there is active flooding, fire, gas smell or a security risk, call the emergency line immediately on 020 7946 0958.</div></Card></div>;
}

export function TenantContractsWorkspace() {
  const [downloaded, setDownloaded] = useState<string | null>(null);
  return <div className="space-y-6"><Card><div className="flex items-center justify-between"><div><h2 className="font-semibold">Document vault</h2><p className="mt-1 text-sm text-gray-500">Your executed agreements, receipts and property reports.</p></div><FileText className="h-6 w-6 text-[#2A5240]" /></div><div className="mt-5 divide-y divide-[#ECEEED]">{docs.map((doc) => <div key={doc[0]} className="flex flex-wrap items-center justify-between gap-4 py-4"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#E8EFEA] p-2 text-[#2A5240]"><FileText className="h-5 w-5" /></div><div><p className="text-sm font-semibold">{doc[0]}</p><p className="text-xs text-gray-500">{doc[1]} · {doc[2]}</p></div></div><button onClick={() => setDownloaded(doc[0])} className="inline-flex items-center gap-2 rounded-xl border border-[#ECEEED] px-3 py-2 text-xs font-semibold hover:bg-[#F0F2F1]"><Download className="h-4 w-4" /> Download</button></div>)}</div></Card>{downloaded && <Toast message={`Download ready: ${downloaded}`} onClose={() => setDownloaded(null)} />}</div>;
}
